name: REDEC
author: LostTeam - Vietnamese by Adam1609
version: 1.0
api: [2.0.0, 1.13.1]
main: LostTeam\Main
description: "Clear all entity but player in your server"
commands:
  h:
    usage: "/h"
    permission: hunt.cmd
    description: "Clear all entity but player in your server"
  hunt:
    usage: "/hunt"
    permission: hunt.cmd
    description: "Clear all entity but player in your server"
permissions:
  hunt.cmd:
    default: op
